-- Sample seed for the historical engineers prototype.
-- Generated from a curated slice of the real OCR'd CSVs.
-- 'NA' sentinel values from the source are imported as SQL NULL.
-- lc_id = 52793 is the 'unknown location' placeholder (filtered from
-- the /places listing and rendered as 'Location unknown' on connection rows).
-- Re-runnable: wipes the four tables then inserts.

PRAGMA foreign_keys = OFF;
DELETE FROM connections;
DELETE FROM people;
DELETE FROM places;
DELETE FROM organizations;
PRAGMA foreign_keys = ON;

-- People --
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (1808, 'john-e-allen', 'John E Allen', 'allen, j e', 'Allen', 'John', 'E');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (5096, 'reuben-e-bakenhus', 'Reuben E Bakenhus', 'bakenhus, r e', 'bakenhus', 'reuben', 'e');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (12280, 'g-h-bowden', 'G H Bowden', 'bowden, g h', 'bowden', 'g', 'h');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (13661, 'charles-jackson-briggs', 'Charles Jackson Briggs', 'briggs, c j', 'briggs', 'charles', 'jackson');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (17805, 'francis-vincent-carey', 'Francis Vincent Carey', 'carey, f v', 'carey', 'francis', 'vincent');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (19420, 'sydney-chambers', 'Sydney Chambers', 'chambers, s', 'chambers', 'sydney', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (20167, 'albert-chester', 'Albert Chester', 'chester, a', 'chester', 'albert', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (23417, 'charles-leonard-conant', 'Charles Leonard Conant', 'conant, c l', 'conant', 'charles', 'leonard');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (24217, 'william-evans-cooper', 'William Evans Cooper', 'cooper, w e', 'cooper', 'william', 'evans');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (26826, 'ida-curtis', 'Ida Curtis', 'curtis, i', 'curtis', 'ida', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (27092, 'alice-evelyn-dacy', 'Alice Evelyn Dacy', 'dacy, a e', 'dacy', 'alice', 'evelyn');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (28119, 'harold-elwood-davis', 'Harold Elwood Davis', 'davis, h e', 'davis', 'harold', 'elwood');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (29235, 'edward-d-densmore', 'Edward D Densmore', 'densmore, e d', 'densmore', 'edward', 'd');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (29878, 'william-palma-dickerman', 'William Palma Dickerman', 'dickerman, w p', 'dickerman', 'william', 'palma');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (31633, 'whitford-drake', 'Whitford Drake', 'drake, w', 'drake', 'whitford', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (32125, 'charles-otto-duevel', 'Charles Otto Duevel', 'duevel, c o', 'duevel', 'charles', 'otto');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (32928, 'rudolf-dzundza', 'Rudolf Dzundza', 'dzundza, r', 'dzundza', 'rudolf', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (33313, 'julius-eberle', 'Julius Eberle', 'eberle, j', 'eberle', 'julius', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (36958, 'olin-burt-fellows', 'Olin Burt Fellows', 'fellows, o b', 'fellows', 'olin', 'burt');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (37782, 'cecil-johnston-finley', 'Cecil Johnston Finley', 'finley, c j', 'finley', 'cecil', 'johnston');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (42177, 'a-e-gees', 'A E Gees', 'gees, a e', 'gees', 'a', 'e');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (44441, 'robert-h-goodell', 'Robert H Goodell', 'goodell, r h', 'goodell', 'robert', 'h');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (48188, 'william-pierson-hammond', 'William Pierson Hammond', 'hammond, w p', 'hammond', 'william', 'pierson');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (53558, 'carl-heinr-hoffmann', 'Carl Heinr Hoffmann', 'hoffmann, c h', 'hoffmann', 'carl', 'heinr');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (53625, 'joh-sam-hofmann', 'Joh Sam Hofmann', 'hofmann, j s', 'hofmann', 'joh', 'sam');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (53808, 'dudley-furber-holden', 'Dudley Furber Holden', 'holden, d f', 'holden', 'dudley', 'furber');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (55917, 'daniel-joseph-hughes', 'Daniel Joseph Hughes', 'hughes, d j', 'hughes', 'daniel', 'joseph');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (60699, 'nicholas-kane', 'Nicholas Kane', 'kane, n', 'kane', 'nicholas', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (68589, 'benjamin-lissberger', 'Benjamin Lissberger', 'lissberger, b', 'lissberger', 'benjamin', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (69480, 'alfred-waldo-lombard', 'Alfred Waldo Lombard', 'lombard, a w', 'lombard', 'alfred', 'waldo');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (70716, 'joseph-richard-lunt', 'Joseph Richard Lunt', 'lunt, j r', 'lunt', 'joseph', 'richard');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (72119, 'john-theodore-mahar', 'John Theodore Mahar', 'mahar, j t', 'mahar', 'john', 'theodore');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (73486, 'perry-foster-marshall', 'Perry Foster Marshall', 'marshall, p f', 'marshall', 'perry', 'foster');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (74841, 'robert-shields-mcclintic', 'Robert Shields Mcclintic', 'mcclintic, r s', 'mcclintic', 'robert', 'shields');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (79093, 'richard-m-mitchell', 'Richard M Mitchell', 'mitchell, r m', 'Mitchell', 'Richard', 'M');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (80069, 'robert-f-moore', 'Robert F Moore', 'moore, r f', 'moore', 'robert', 'f');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (82183, 'francisco-narvaez', 'Francisco Narvaez', 'narvaez, f', 'narvaez', 'francisco', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (82308, 'juan-r-navarro', 'Juan R Navarro', 'navarro, j r', 'navarro', 'juan', 'r');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (89042, 'edgar-lockwood-perry', 'Edgar Lockwood Perry', 'perry, e l', 'perry', 'edgar', 'lockwood');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (89419, 'max-pfaltz', 'Max Pfaltz', 'pfaltz, m', 'pfaltz', 'max', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (104159, 'charlotte-victorine-simonds', 'Charlotte Victorine Simonds', 'simonds, c v', 'simonds', 'charlotte', 'victorine');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (107386, 'david-louis-steidlitz', 'David Louis Steidlitz', 'steidlitz, d l', 'steidlitz', 'david', 'louis');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (107536, 'eduard-alexis-stephani', 'Eduard Alexis Stephani', 'stephani, e a', 'stephani', 'eduard', 'alexis');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (109663, 'raymond-carl-svenson', 'Raymond Carl Svenson', 'svenson, r c', 'svenson', 'raymond', 'carl');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (115457, 'nicolaus-v-kournakow', 'Nicolaus V Kournakow', 'v kournakow, n', 'v kournakow', 'nicolaus', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (117111, 'isaac-parker-wainwright', 'Isaac Parker Wainwright', 'wainwright, i p', 'wainwright', 'isaac', 'parker');
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (117978, 'morton-ware', 'Morton Ware', 'ware, m', 'ware', 'morton', NULL);
INSERT INTO people (in_id, slug, name, simpname, lastname, firstname, middlename) VALUES (123340, 'charles-h-wright', 'Charles H Wright', 'wright, c h', 'Wright', 'Charles', 'H');

-- Places (includes synthetic lc_id=52793 placeholder) --
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (6, 'mittelsachsen-sachsen-deutschland', 'Mittelsachsen, Sachsen, Deutschland', 'germany', 50.91404, 13.33723);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (7, 'tarrant-county-texas-united-states', 'Tarrant County, Texas, United States', 'united states of america', 32.8294337, -97.2134822);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (9, 'council-of-the-city-of-sydney-new-south-wales-australia', 'Council of the City of Sydney, New South Wales, Australia', 'australia', -33.8688197, 151.2092955);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (14, 'suffolk-county-massachusetts-united-states', 'Suffolk County, Massachusetts, United States', 'united states of america', 42.3600825, -71.0588801);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (33, 'sullivan-county-east-tennessee-tennessee-united-states', 'Sullivan County, East Tennessee, Tennessee, United States', 'united states of america', 36.5951059, -82.1887444);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (44, 'new-york-county-city-of-new-york-new-york-united-states', 'New York County, City of New York, New York, United States', NULL, 40.7127753, -74.0059728);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (56, 'midland-county-texas-united-states', 'Midland County, Texas, United States', 'united states of america', 31.99735, -102.0779);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (72, 'staffordshire-england-united-kingdom', 'Staffordshire, England, United Kingdom', 'united kingdom', 52.87927, -2.057187);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (87, 'city-of-johannesburg-metropolitan-municipality-gauteng-south-africa', 'City of Johannesburg Metropolitan Municipality, Gauteng, South Africa', 'south africa', -26.2041, 28.04731);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (100, 'cardiff-cymru-wales-cf-united-kingdom', 'Cardiff, Cymru / Wales, CF, United Kingdom', 'united kingdom', 51.481581, -3.17909);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (151, 'phelps-county-missouri-united-states', 'Phelps County, Missouri, United States', 'united states of america', 37.9642529, -91.8318334);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (152, 'northampton-county-pennsylvania-united-states', 'Northampton County, Pennsylvania, United States', 'united states of america', 40.625932, -75.370458);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (294, 'huntingdon-county-pennsylvania-united-states', 'Huntingdon County, Pennsylvania, United States', 'united states of america', 40.415527, -78.019539);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (329, 'lafayette-parish-louisiana-united-states', 'Lafayette Parish, Louisiana, United States', 'united states of america', 30.1802335, -92.0781648);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (409, 'centre-county-pennsylvania-united-states', 'Centre County, Pennsylvania, United States', 'united states of america', 40.79445, -77.861639);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (1165, 'tartu-maakond-eesti', 'Tartu maakond, Eesti', 'estonia', 58.377983, 26.7290383);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (1246, 'forsyth-county-north-carolina-united-states', 'Forsyth County, North Carolina, United States', 'united states of america', 36.103964, -80.254435);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (5511, 'place-5511', NULL, NULL, 0.0, 0.0);
INSERT INTO places (lc_id, slug, locn, country, lat, lon) VALUES (52793, 'location-unknown', NULL, NULL, NULL, NULL);

-- Organizations --
INSERT INTO organizations (og_id, slug, org, company) VALUES (6, 'bergakademie-freiberg', 'Bergakademie Freiberg', NULL);
INSERT INTO organizations (og_id, slug, org, company) VALUES (16, 'mit', 'Mit', NULL);
INSERT INTO organizations (og_id, slug, org, company) VALUES (80, 'hygrade-sylvania-corp', 'Hygrade Sylvania Corp', NULL);
INSERT INTO organizations (og_id, slug, org, company) VALUES (82, 'cu', 'Cu', NULL);
INSERT INTO organizations (og_id, slug, org, company) VALUES (216, 'pretoria-gold-mining-company', 'Pretoria Gold Mining Company', 'Pretoria Gold Mining Company');
INSERT INTO organizations (og_id, slug, org, company) VALUES (289, 'bedwas-navlgatlon-colliery-limited', 'Bedwas Navlgatlon Colliery Limited', 'Bedwas Navlgatlon Colliery Limited');
INSERT INTO organizations (og_id, slug, org, company) VALUES (290, 'east-cannock-colliery-company', 'East Cannock Colliery Company', 'East Cannock Colliery Company');
INSERT INTO organizations (og_id, slug, org, company) VALUES (534, 'coetzeestroom-estate-gold-mining-limited', 'Coetzeestroom Estate Gold Mining Limited', 'Coetzeestroom Estate Gold Mining Limited');
INSERT INTO organizations (og_id, slug, org, company) VALUES (1509, 'westralia-united-goldfields-limited', 'Westralia United Goldfields Limited', 'Westralia United Goldfields Limited');
INSERT INTO organizations (og_id, slug, org, company) VALUES (4131, 'askern-coal-and-iron-company', 'Askern Coal And Iron Company', 'Askern Coal And Iron Company');
INSERT INTO organizations (og_id, slug, org, company) VALUES (4440, 'csub-of-camp-bird-limited', 'Csub. Of Camp Bird Limited', 'Csub. Of Camp Bird Limited');
INSERT INTO organizations (og_id, slug, org, company) VALUES (6625, 'sudan-gold-field-company', 'Sudan Gold Field Company', 'Sudan Gold Field Company');
INSERT INTO organizations (og_id, slug, org, company) VALUES (7948, 'new-nora-iron-mines-limited', 'New Nora Iron Mines Limited', 'New Nora Iron Mines Limited');
INSERT INTO organizations (og_id, slug, org, company) VALUES (8108, 'national-tube-co', 'National Tube Co.', 'National Tube Co.');
INSERT INTO organizations (og_id, slug, org, company) VALUES (8604, 'salisbury-gold-mining-company', 'Salisbury Gold Mining Company', 'Salisbury Gold Mining Company');
INSERT INTO organizations (og_id, slug, org, company) VALUES (11314, 'virginia-transvaal-gold-mining-and', 'Virginia Transvaal Gold Mining And', 'Virginia Transvaal Gold Mining And');
INSERT INTO organizations (og_id, slug, org, company) VALUES (14909, 'engineers', 'Engineers', NULL);
INSERT INTO organizations (og_id, slug, org, company) VALUES (18691, 'bonanza-mines-co', 'Bonanza Mines Co.', 'Bonanza Mines Co.');
INSERT INTO organizations (og_id, slug, org, company) VALUES (19433, 'grasselli-chemical-co', 'Grasselli Chemical Co.', 'Grasselli Chemical Co.');
INSERT INTO organizations (og_id, slug, org, company) VALUES (27397, 'la-union-milling-co', 'La Union Milling Co.', 'La Union Milling Co.');
INSERT INTO organizations (og_id, slug, org, company) VALUES (32167, 'tiverton-technical-school', 'Tiverton Technical School', NULL);
INSERT INTO organizations (og_id, slug, org, company) VALUES (33237, 'newtown-county-intermediate', 'Newtown County Intermediate', NULL);
INSERT INTO organizations (og_id, slug, org, company) VALUES (52793, 'org-unknown', NULL, NULL);

-- Connections (fact table) --
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (29235, 14909, 14, 1893, 'Of Densmore & Le Clear', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (29235, 52793, 5511, 1893, 'student', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (29235, 16, 5511, 1940, NULL, 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (107536, 52793, 1165, 1865, NULL, 'frei', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (107536, 6, 6, 1866, 'student', 'frei', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (69480, 52793, 5511, 1898, 'student', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (69480, 16, 5511, 1930, 'dept', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (12280, 7948, 9, 1915, 'board', 'myb', 'corpis', NULL, NULL, 'G. H. Bowden.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (12280, 4131, 5511, 1920, 'board', 'myb', 'corpis', NULL, NULL, '00 . G. H. Bowden.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (12280, 4131, 33, 1921, 'board', 'myb', 'corpis', NULL, NULL, '8. Instone, Chairman. I M. P. Davis. I R. Bennett. I Col. G. H. Bowden.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (12280, 289, 100, 1922, 'engineer', 'myb', 'corpis', NULL, NULL, 'A. Instone. | M. Davis. Consulting Engineer G. H. Bowden, M.I.Mech.E., 17, Victoria Street, S.W. 1. Mine Manager H. Bradshaw. Agent W. Thomas.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (12280, 4131, 7, 1923, 'board', 'myb', 'corpis', NULL, NULL, 'Directors Qualification, Â£1,050 . Sir S. Instone, Chairman. I M. P. Davis. I R. Bennett. I G. H. Bowden.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (109663, 80, 1246, 1936, 'student', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (109663, 16, 1246, 1940, 'Engineer', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (37782, 52793, 294, 1884, NULL, 'taime', 'professional', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (37782, 52793, 409, 1886, NULL, 'taime', 'professional', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (37782, 52793, 152, 1892, NULL, 'taime', 'professional', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (37782, 52793, 152, 1902, NULL, 'taime', 'professional', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (37782, 52793, 5511, 1912, NULL, 'columbia', 'alumni', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (123340, 52793, 5511, 1879, NULL, 'worcester', 'alumni', 'civil eng', NULL, 'Wright, Charles H. C.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (123340, 52793, 5511, 1890, NULL, 'colorado', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (123340, 290, 72, 1911, 'board', 'myb', 'corpis', NULL, NULL, 'Btephen Stokes, J.P., Chairman. | Edward Land. I Ciias. H. Wright, J.P. | Thomas A. Stokes.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (123340, 290, 72, 1912, 'board', 'myb', 'corpis', NULL, NULL, 'Stephen Stokes, J.P., Chairman. | Edward Land. I Chas. H. Wright, J.P. I Thomas A. Stokes.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (123340, 1509, 56, 1912, 'board', 'myb', 'corpis', NULL, NULL, 'C. H. Wright, J. P. | A.W.iss.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (32125, 52793, 329, 1924, 'student', 'MIT', 'alumni', 'general', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (32125, 52793, 5511, 1924, 'student', 'MIT', 'alumni', 'general', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (32125, 16, 329, 1930, 'chief engr', 'MIT', 'alumni', 'general', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (32125, 16, 5511, 1940, 'Engineer', 'MIT', 'alumni', 'general', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (19420, 534, 9, 1894, 'chair', 'myb', 'corpis', NULL, NULL, 'Sydney Chambers, Chairman.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (19420, 11314, 9, 1894, 'board', 'myb', 'corpis', NULL, NULL, 'Alfred Jones. | M. W. Colchester-Wemyss, J.P. | Edward Chambers. | Sydney Chambers.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (19420, 6625, 9, 1909, 'board', 'myb', 'corpis', NULL, NULL, 'Directors Qualification, Â£200 . John S. H. Lomas, Chairman. | Sydney A. Chambers. | Henry D. Elin. | H. E. M. Bourkej');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (19420, 216, 87, 1910, 'chair', 'myb', 'corpis', NULL, NULL, 'S. Chambers, Chairman. | C. A. Chidcll. | John S. Khclrtrick. Agent in South Africa K. Orr, Cnwtle Brewery, Johannesburg.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (19420, 8604, 9, 1910, 'board', 'myb', 'corpis', NULL, NULL, 'W. G. Izard. | Sydney Chambers.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (73486, 52793, 5511, 1914, 'student', 'MIT', 'alumni', 'chemistry', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (73486, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'chemistry', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (74841, 52793, 151, 1929, 'student', 'MIT', 'alumni', 'business', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (74841, 16, 151, 1930, 'student engr', 'MIT', 'alumni', 'business', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (42177, 18691, 5511, 1920, 'Pres', 'amm', 'corpis', NULL, NULL, 'A. E. Gees, (.â€˜aney, Kas.. Pres.; C. E. Angeli, Independence, Kas., S');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (42177, 18691, 5511, 1922, 'Pres', 'amm', 'corpis', NULL, NULL, 'A. E. Gees, Caney, Kans., Pres.; C. E. Angeli, Independence, Secy.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (31633, 52793, 44, 1911, 'student', 'MIT', 'alumni', 'naval eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (31633, 16, 44, 1930, NULL, 'MIT', 'alumni', 'naval eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (53808, 82, 44, 1896, 'student', 'cu', 'alumni', 'student', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (53808, 52793, 5511, 1917, 'student', 'MIT', 'alumni', 'business', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (53808, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'business', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (82183, 27397, 5511, 1911, 'Manager', 'amm', 'corpis', NULL, NULL, 'Francisco Narvaez, Manager. Chilean Mills and 150-ton Cyanide Plant.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (82183, 4440, 5511, 1919, 'General Manager', 'amm', 'corpis', NULL, NULL, 'Francisco Narvaez, General Manager.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (55917, 52793, 44, 1930, 'student', 'MIT', 'alumni', 'aeronautical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (55917, 16, 44, 1940, 'Engineer', 'MIT', 'alumni', 'aeronautical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (117978, 32167, 5511, 1896, 'teacher', 'rsm', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (117978, 33237, 5511, 1896, 'assistant', 'rsm', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (117978, 52793, 5511, 1896, NULL, 'rsm', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (68589, 8108, 44, 1920, 'Pres', 'amm', 'corpis', NULL, NULL, 'Benjamin Lissberger, New York, Pres.; W. A. Mitchell, Secretary.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (68589, 19433, 44, 1922, 'Pres', 'amm', 'corpis', NULL, NULL, 'Benjamin Lissberger, New York, Pres.; W. A. Mitchell, Secretary.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (23417, 52793, 5511, 1894, 'student', 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (23417, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (89042, 52793, 44, 1926, 'student', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (89042, 16, 44, 1930, 'engr', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (29878, 52793, 5511, 1922, 'student', 'MIT', 'alumni', 'business', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (29878, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'business', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (82308, 82, 44, 1880, 'student', 'cu', 'alumni', 'student', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (82308, 82, 44, 1909, 'student', 'cu', 'alumni', 'student', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (13661, 52793, 5511, 1910, 'student', 'MIT', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (13661, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (27092, 52793, 5511, 1902, 'student', 'MIT', 'alumni', 'biology', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (27092, 16, 5511, 1940, NULL, 'MIT', 'alumni', 'biology', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (79093, 52793, 5511, 1901, NULL, 'worcester', 'alumni', 'mechanical eng', NULL, 'Mitchell, Richard M.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (79093, 52793, 5511, 1919, 'student', 'MIT', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (79093, 16, 5511, 1930, NULL, 'MIT', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (70716, 52793, 5511, 1914, 'student', 'MIT', 'alumni', 'sanitary', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (70716, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'sanitary', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (53625, 6, 6, 1786, 'student', 'frei', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (53625, 52793, 6, 1837, 'master', 'frei', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (36958, 52793, 44, 1913, 'student', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (36958, 16, 44, 1930, NULL, 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (5096, 52793, 44, 1896, 'student', 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (5096, 16, 44, 1930, 'civil engr', 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (5096, 16, 44, 1940, 'Consulting', 'MIT', 'alumni', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (26826, 16, 14, 1896, 'student', 'MIT', 'alumni', 'chemistry', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (26826, 52793, 5511, 1918, 'student', 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (26826, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'electrical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (104159, 52793, 5511, 1913, 'student', 'MIT', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (104159, 16, 5511, 1930, NULL, 'MIT', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (60699, 52793, 5511, 1923, 'student', 'MIT', 'alumni', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (60699, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (28119, 16, 44, 1895, 'student', 'MIT', 'alumni', 'architect', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (28119, 52793, 5511, 1895, 'student', 'MIT', 'alumni', 'architect', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (28119, 52793, 5511, 1925, 'student', 'MIT', 'alumni', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (28119, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (28119, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'architect', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (17805, 52793, 5511, 1908, 'student', 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (17805, 16, 5511, 1930, NULL, 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (117111, 52793, 5511, 1869, 'student', 'MIT', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (117111, 16, 5511, 1930, NULL, 'MIT', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (107386, 52793, 44, 1921, 'student', 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (107386, 16, 44, 1930, 'proprietor', 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (80069, 52793, 5511, 1941, NULL, 'colorado', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (115457, 6, 6, 1883, 'student', 'frei', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (20167, 52793, 5511, 1870, NULL, 'columbia', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (32928, 6, 6, 1920, 'student', 'frei', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (1808, 52793, 5511, 1915, NULL, 'worcester', 'alumni', 'civil eng', NULL, 'Allen, John E. C.');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (44441, 52793, 5511, 1902, NULL, 'colorado', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (53558, 6, 6, 1813, 'student', 'frei', 'alumni', 'mining eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (89419, 6, 6, 1881, 'student', 'frei', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (48188, 52793, 5511, 1934, NULL, 'columbia', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (72119, 16, 14, 1907, 'student', 'MIT', 'alumni', 'civil eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (33313, 6, 6, 1898, 'student', 'frei', 'alumni', NULL, NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (24217, 52793, 44, 1922, 'student', 'MIT', 'alumni', 'mechanical eng', NULL, NULL);
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (1808, 6, 52793, 1898, 'engineer', 'myb', 'corpis', NULL, NULL, 'Connection where the source did not identify a place; lc_id 52793 stands in for "unknown location".');
INSERT INTO connections (in_id, og_id, lc_id, year, position, source, type, edu, nationality, text) VALUES (5096, 6, 6, NULL, NULL, 'frei', NULL, NULL, NULL, NULL);
